name: build BRLTTY for Windows

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build_brltty:
    
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Set up MSYS environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          # update: true
          install: >-
            autoconf
            automake
            make
            tcl
            awk
            bison
            groff
            m4
            patch
            mingw-w64-i686-pdcurses
            mingw-w64-i686-icu
            mingw-w64-i686-tcl
            mingw-w64-i686-winpthreads-git
            mingw-w64-i686-libiconv
            mingw-w64-i686-toolchain
            mingw-w64-i686-python
            mingw-w64-i686-python-setuptools
            mingw-w64-i686-cython
      - uses: actions/checkout@v3
      
      - name: Build BRLTTY
        run: |
          patch -p0 <"Windows/affinity.patch"  
          ./autogen
          ./cfg-windows --prefix=/ --enable-relocatable-install --with-usb-package=libusb-1.0
          make
          make -C Documents
          mkdir install
          make install install-messages JAVA_JAR_DIR=/lib JAVA_JNI_DIR=/lib     PYTHON_PREFIX="Python" INSTALL_ROOT="./install"
          cp Documents/brltty.conf install/etc/
          cp Programs/*.exe Programs/*.dll install/bin
          cp Bindings/Python/dist/* install/Python/
          cp LICENSE-LGPL install/LICENSE-LGPL.txt
          cp Documents/*.csv install/etc/
          cp Programs/*.bat install/
          cp /mingw32/bin/{libgcc_s_dw2-1.dll,libiconv-2.dll,libpdcurses*.dll,libintl-8.dll} install/bin/
          cd install/
          rm -f "bin/brltty-config"
          rm -f "etc/brlapi.key"

      - uses: actions/upload-artifact@v3
        with:
          name: brltty
          path: .
